baseURL = "https://superzscy.github.io/"
languageCode = "zh-cn"
title = "小虾米日记"
theme = "zozo"
summaryLength = 100
paginate = 4                         # shows the number of articles  # 首页显示文章数量

[params]
  keywords = ["Hugo", "theme","zozo"]                                  # site's keywords  # 网站关键字
  description = "Hugo theme zozo example site."                        # site's description  # 网站描述